config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :home_sections do
      collection do
        post :update_positions
      end
    end
  end
end

app/models/spree/home_section.rb
module Spree
  class HomeSection < Spree::Base
    include Spree::ProductIdsProcessable
    acts_as_list

    has_many :home_section_products, dependent: :destroy
    has_many :products, through: :home_section_products, source: :product

    alias_attribute :sections, :home_section_products

    after_save :force_delete_sections, :add_products_by_id

    attr_accessor :product_ids, :force_delete

    def delete_sections
      home_section_products.delete_all
    end

    def product_ids?
      product_ids.present?
    end

    def force_delete?
      force_delete.present?
    end

    def products_by_position
      products.order(sections_asc_query)
    end

    def section_products?
      home_section_products.any?
    end

    protected

    def force_delete_sections
      return unless force_delete?

      delete_sections
    end

    def add_products_by_id
      return unless product_ids?

      add_products(product_ids: product_ids)
    end

    private

    def sections_asc_query
      'spree_home_section_products.position ASC'
    end
  end
end

app/models/spree/home_section_product.rb
module Spree
  class HomeSectionProduct < Spree::Base
    acts_as_list scope: :home_section

    belongs_to :home_section, class_name: 'Spree::HomeSection', required: true
    belongs_to :product, class_name: 'Spree::Product', required: true
  end
end

app/models/spree/product_decorator.rb
module Spree
  module ProductDecorator
    def self.prepended(base)
      base.has_many :home_section_products,
                    class_name: 'Spree::HomeSectionProduct'

      base.has_many :home_sections,
                    through: :home_section_products,
                    class_name: 'Spree::HomeSection'
    end

    def image_url(style: :product)
      image = images.first
      return if image.blank?

      image.url(style)
    end

    def presenter_attributes
      {
        id: id,
        name: name,
        image: image_url(style: :mini)
      }
    end
  end
end

Spree::Product.prepend Spree::ProductDecorator

app/controllers/spree/admin/base_controller_decorator.rb
module Spree
  module Admin
    module BaseControllerDecorator
      Spree::Admin::BaseController.include(Spree::Admin::HomeSectionHelper)

      def self.prepended(base)
        base.helper_method :parse_home_sections
      end
    end
  end
end

Spree::Admin::BaseController.prepend Spree::Admin::BaseControllerDecorator

app/controllers/spree/admin/home_sections_controller.rb
module Spree
  module Admin
    class HomeSectionsController < ResourceController
    end
  end
end

app/helpers/spree/admin/home_section_helper.rb
module Spree
  module Admin
    module HomeSectionHelper
      def parse_home_sections(home_section)
        return [] unless home_section.section_products?

        parse_products(products: home_section.products_by_position)
      end

      def parse_products(products:)
        products.map { |product| product_presenter(product: product).as_json }
      end

      def product_presenter(product:)
        presenter(product).parse
      end

      private

      def presenter(product)
        Spree::EasyHomepage::ProductPresenter.new(
          product: product,
          main_app: main_app
        )
      end
    end
  end
end

app/helpers/spree/easy_homepage_helper.rb
module Spree
  module EasyHomepageHelper
    def fill_with_sections(partial: home_section_partial, **partial_args)
      get_homesection_partial(partial: partial, **partial_args)
    end

    def home_sections
      Spree::HomeSection.all
    end

    private

    def get_homesection_partial(partial: home_section_partial, **partial_args)
      render(partial: partial, **partial_args, cached: true)
    end

    def home_section_partial
      'spree/shared/home_sections'
    end

    def feature_home_section
      'spree/shared/feature_sections'
    end
  end
end

# Author note:
# This helper and the homesection partial view, violates a few OOP principles
# I plan to change this when I have time to do so.
# Although I don't plan to change the public interface,
# the private interface will.
# for example, instead of calling render,
# a new Presenter or Service object would instead be called

app/views/spree/admin/home_section_products/_line_item.js.erb
<script type='text/template' id='product-search-lineitem'>
  <tr data-hook='home_sections_products_row'>
    <input name="home_section[product_ids][]" type="hidden" value="{{product.id}}" />
    <td class='move-handle handle grabbable'>
      <span class='icon icon-move'></span>
    </td>
    <td>
      {{#if product.image }}
        <img src='{{product.image}}' class='thumbnail mb-0' />
      {{ else }}
        <img src='<%= image_path('noimage/mini.png') %>' class='thumbnail mb-0' />
      {{/if}}
    </td>
    <td>
      <strong></strong>
        {{#if product.path }}
          <a target='_blank' href='{{product.path}}'>{{product.name}}</a>
        {{else}}
          {{product.name}}
        {{/if}}
    </td>
    <td class='actions actions-2 text-right'>
      <%= link_to_delete('#', {no_text: true, url: '#', data: {}}) %>
    </td>
  </tr>
</script>

app/views/spree/admin/home_sections/_form.html.erb
<%= render partial: 'spree/shared/error_messages', locals: { target: @home_section } %>

<%= render partial: 'spree/admin/home_section_products/line_item', formats: :js %>
<%= render partial: 'spree/admin/products/autosearch', formats: :js %>

<div class="form-group">
  <%= f.field_container :title, class: ['form-group'] do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control title' %>
    <%= f.error_message_on :title %>
  <% end %>
</div>

<div class="form-group">
  <table class="table">
    <thead data-hook="home_sections_product_header">
      <tr>
        <th></th>
        <th><%= Spree.t(:image) %></th>
        <th><%= plural_resource_name(Spree::Product) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <%= content_tag :tbody,
      id: "section-product-list",
      data: {
        home_sections: parse_home_sections(@home_section)
    } do %>

    <% end %>
  </table>
</div>

<%= hidden_field_tag 'home_section[force_delete]', true %>

<div class="card mb-3">
  <div class="card-header">
    <h1 class="card-title mb-0 h5"><%= Spree.t(:add_product) %></h1>
  </div>
  <div class="card-body">
    <div class="form-group">
      <%= label_tag :product_search, Spree.t(:name_or_sku) %>
      <%= hidden_field_tag :product_search, "",
        class: "product-autosearch d-block w-100"
      %>
    </div>
  </div>
</div>

app/views/spree/admin/home_sections/edit.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(plural_resource_name(Spree::HomeSection)), spree.admin_home_sections_url %> /
  <%= @home_section.title %>
<% end %>

<%= form_for [:admin, @home_section] do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/home_sections/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::HomeSection) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_home_section), new_object_url, { class: "btn-success", icon: 'add', id: 'admin_new_home_section' } %>
<% end if can?(:create, Spree::HomeSection) %>

<% if @home_sections.any? %>
  <table class="table sortable" data-sortable-link="<%= update_positions_admin_home_sections_url %>">
    <thead data-hook="home_sections_header">
      <tr>
        <th></th>
        <th><%= I18n.t(:title, scope: 'activerecord.attributes.spree/home_section') %></th>
        <th><%= plural_resource_name(Spree::Product) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @home_sections.each do |home_section| %>
        <tr id="<%= spree_dom_id home_section %>"  data-hook="home_sections_row">
          <td class="move-handle handle grabbable">
            <% if can? :edit, home_section %>
              <span class="icon icon-move"></span>
            <% end %>
          </td>
          <td><%= home_section.title %></td>
          <td>
            <%= home_section.products.count %>
            <%= I18n.t('activerecord.models.spree/product', count: home_section.products.count) %>
            <%= '-' if home_section.products.any? %>
            <% home_section.products_by_position.each_with_index do |product, index| %>
              <%= link_to "\"#{product.try(:name)}\"", edit_admin_product_path(product), target: '_blank' %>
              <%= ', ' if index < home_section.products.count - 1 %>
            <% end %>
          </td>
          <td class="actions actions-2 text-right">
            <%= link_to_edit(home_section, no_text: true) if can?(:edit, home_section) %>
            <%= link_to_delete(home_section, no_text: true) if can?(:destroy, home_section) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found alert alert-info">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::HomeSection)) %>
    <% if can?(:create, Spree::HomeSection) %>
      - <%= link_to(Spree.t(:add_one), spree.new_admin_home_section_path(@home_section)) %>!
    <% end %>
  </div>
<% end %>

app/views/spree/admin/home_sections/new.html.erb
<% content_for :page_title do %>
  <%= link_to plural_resource_name(Spree::HomeSection), spree.admin_home_sections_url %> /
  <%= Spree.t(:new_home_section) %>
<% end %>

<%= form_for [:admin, @home_section] do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/products/_autosearch.js.erb
<script type='text/template' id='product-search-result'>
  <div class='variant-autocomplete-item media align-items-center'>
    <figure class='variant-image media-left mb-0 mr-3'>
      {{#if product.image }}
        <img src='{{product.image}}' class="thumbnail mb-0" />
      {{ else }}
        <img src='<%= image_path("noimage/mini.png") %>' class="thumbnail mb-0" />
      {{/if}}
    </figure>

    <div class='variant-details media-body'>
      <h5 class="variant-name media-heading h6 mb-0">{{product.name}}</h5>
      <strong><%= Spree.t(:sku) %>:</strong> {{product.sku}}
    </div>
  </div>
</script>

app/views/spree/shared/_home_sections.html.erb
<% product_partial ||= 'spree/products/product' %>
<% product_locals ||= {} %>

<% home_sections.each do |section| %>
  <div class="row text-center">
    <div class="col-sm-12">
      <h2> <%= section.title %> </h2>
    </div>
  </div>
  <div class="row">
    <% section.products_by_position.each do |product| %>
      <% locals = {product: product, taxon: @taxon || nil}.merge(product_locals) %>
      <%= render partial: product_partial, locals: locals %>
    <% end %>
  </div>
<% end %>